"""Initial migration

Revision ID: 959a99d18006
Revises: 
Create Date: 2025-05-08 17:00:56.517486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959a99d18006'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergies',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('planet', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('origin_planet', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_allergies',
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('allergy', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['allergy'], ['allergies.name'], ),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], )
    )
    op.create_table('meal_ingredients',
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('ingredient', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient'], ['ingredients.name'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], )
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=False),
    sa.Column('completed_time', sa.DateTime(), nullable=True),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('meal_ingredients')
    op.drop_table('hero_allergies')
    op.drop_table('meals')
    op.drop_table('ingredients')
    op.drop_table('heroes')
    op.drop_table('allergies')
    # ### end Alembic commands ###
